name: Deploy NadekoBot Docs

on:
  push:
    branches: ["v6"]
    paths:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    if: ${{ github.repository == 'nadeko-bot/nadekobot' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
          cache-dependency-path: 'docs/mkdocs-requirements.txt'

      - name: Install project dependencies
        run: pip install -r docs/mkdocs-requirements.txt

      - name: Build the site with MkDocs
        working-directory: ./docs
        run: mkdocs build --strict

      - name: Deploy to GitHub Pages
        working-directory: ./docs
        run: mkdocs gh-deploy --force
